name: Run Babilon_M Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Python Actions Collection
        uses: microsoft/action-python@0.2.0


  setting:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      
  
#   testing:
#    runs-on: ubuntu-latest
#    steps:
#      - name: actions-pytest
#        uses: xoviat/actions-pytest@0.1-alpha2

#      - uses: actions/checkout@v3
#      - name: Install poetry
#        run: pipx install poetry
#      - uses: actions/setup-python@v4
#        with:
#         python-version: '3.9'
#         cache: 'poetry'
#      - run: poetry install
#      - run: poetry run pytest
