name: Run Babilon_M Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Python Actions Collection
        uses: microsoft/action-python@0.2.0


  testing:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
